### ISSUE TITLE
CI should check the JSON against the token list schema

### ISSUE THREAD

**Issue by mhluongo** [tallycash/token-list#2]

**Comment by 0xzoz** [comment]
How should this be done? Github actions or you have another system you would prefer/are using?

**Comment by mhluongo** [comment]
Github actions for sure. Here's the [extension build](https://github.com/tallycash/extension/blob/main/.github/workflows/build.yml) to give you an idea of the current state of play. Also have a bunch going public soon with the smart contracts.
